"""Example data."""

example1 = """>example Small but realistic PredictAll example
AMNTDLKLPAGKTMTIEDVKQLLERYQMALKKTGEQLGWAYEQAAFPYTVRIHESVLYL
QGDGRLYKGMAISVRTAGEETFIDIALPPGATHGDKGKANEFSKWLAKTLGGELHLFSG
RTMVFGSA
"""
